### ISSUE TITLE
Bug: Compilation error

### ISSUE THREAD

**Issue by LucasSnatiago** [IsabelaBB/iDISF#2]
If it is possible, please add an Dockerfile to this project.

Code does not compile in Arch Linux: 6.6.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 29 Nov 2023 00:37:40 +0000 x86_64 GNU/Linux

```
(iDISF) [lucas@Lucas-PC iDISF]$ python3.10 -m pip install python3/.
Processing ./python3
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: iDISF
  Building wheel for iDISF (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      In file included from /home/lucas/.local/share/virtualenvs/iDISF-3hYUVbwY/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /home/lucas/.local/share/virtualenvs/iDISF-3hYUVbwY/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /home/lucas/.local/share/virtualenvs/iDISF-3hYUVbwY/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from iDISF_py3.c:15:
      /home/lucas/.local/share/virtualenvs/iDISF-3hYUVbwY/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      iDISF_py3.c:17:10: fatal error: Image.h: No such file or directory
         17 | #include "Image.h"
            |          ^~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for iDISF
  Running setup.py clean for iDISF
Failed to build iDISF
ERROR: Could not build wheels for iDISF, which is required to install pyproject.toml-based projects
```

**Comment by IsabelaBB** [comment]
Hi, Lucas. What's your Ubuntu version? 

Maybe the `lidisf` is missing. After compiling iDISF in C, do you have the file `lib/libidisf.a`? 
If not, run `make lib` and try again. 

In Ubuntu 24, it may be required to replace `distutils.core` with `setuptools`. Install the version 58.2.0: `pip install setuptools==58.2.0`.

If the error persists, delete the env (`pipenv --rm`) and create a new one.

**Comment by LucasSnatiago** [comment]
Hello, @IsabelaBB. I'm not using Ubuntu. I'm actually using ArchLinux, so the commands can differ. I opened this issue some time ago, at this time something was broken in the asdf package on Arch (I think). I tried your application again and it's working. Maybe it was a bug in the tools I was using. So, you can just close this issue as it does not happen anymore. If you read the error message the problem was happening in python 3.10 when it calls GCC. I tried again using python 3.10.6 and worked flawlessly.
